services:
  mysql:
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=vollmed
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=test
    ports:
      - 3306:3306